In [1]:
##check numpy version
import numpy as np
#id, 2d,3d,4d



In [3]:
lst=[1,2,"3",4,5]
ar1=np.array(lst)
ar1

array(['1', '2', '3', '4', '5'], dtype='<U21')

In [5]:
arr3 =np.ones(5) #convert in 
arr3

array([1., 1., 1., 1., 1.])

In [6]:
arr4= np.zeros((2,3)) #to check the dimension of error we can count brackets in output
arr4


array([[0., 0., 0.],
       [0., 0., 0.]])

In [9]:
arr5=np.linspace(1,50,100) #range and divide
arr5

array([ 1.        ,  1.49494949,  1.98989899,  2.48484848,  2.97979798,
        3.47474747,  3.96969697,  4.46464646,  4.95959596,  5.45454545,
        5.94949495,  6.44444444,  6.93939394,  7.43434343,  7.92929293,
        8.42424242,  8.91919192,  9.41414141,  9.90909091, 10.4040404 ,
       10.8989899 , 11.39393939, 11.88888889, 12.38383838, 12.87878788,
       13.37373737, 13.86868687, 14.36363636, 14.85858586, 15.35353535,
       15.84848485, 16.34343434, 16.83838384, 17.33333333, 17.82828283,
       18.32323232, 18.81818182, 19.31313131, 19.80808081, 20.3030303 ,
       20.7979798 , 21.29292929, 21.78787879, 22.28282828, 22.77777778,
       23.27272727, 23.76767677, 24.26262626, 24.75757576, 25.25252525,
       25.74747475, 26.24242424, 26.73737374, 27.23232323, 27.72727273,
       28.22222222, 28.71717172, 29.21212121, 29.70707071, 30.2020202 ,
       30.6969697 , 31.19191919, 31.68686869, 32.18181818, 32.67676768,
       33.17171717, 33.66666667, 34.16161616, 34.65656566, 35.15

In [11]:
arr6=np.arange(1,31).reshape(5,6)
arr6

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30]])

In [ ]:
arr7=np.random.randint(1,100,10)

In [16]:
arr8=np.arange(60).reshape((12,5))
print(arr8.shape)
'''arr8.shape
arr8.dtype
arr8.size
arr8.ndim'''
arr9=arr8.T.shape
arr9

(12, 5)


(5, 12)

In [14]:
arr8.ravel() #multidimension ko single dimension me convert karta h
arr8.flatten()


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59])

In [17]:
#indexing and slicing
# id array
arr=np.array((1,2,3,4,5))
arr[3]



np.int64(4)

In [18]:
##2d array
#indexing and slicing ----[rowstarting: row end :rowskip, col start :colend : colskip]
arr10=np.arange(1,61).reshape(6,10)
print(arr10)
arr10[3:6,2:]
arr10[3:4,2:3]=100

[[ 1  2  3  4  5  6  7  8  9 10]
 [11 12 13 14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27 28 29 30]
 [31 32 33 34 35 36 37 38 39 40]
 [41 42 43 44 45 46 47 48 49 50]
 [51 52 53 54 55 56 57 58 59 60]]


In [19]:
arr8[9:10,4:5][0][0]

np.int64(49)

In [20]:
arr8[::-1,::-1]

array([[59, 58, 57, 56, 55],
       [54, 53, 52, 51, 50],
       [49, 48, 47, 46, 45],
       [44, 43, 42, 41, 40],
       [39, 38, 37, 36, 35],
       [34, 33, 32, 31, 30],
       [29, 28, 27, 26, 25],
       [24, 23, 22, 21, 20],
       [19, 18, 17, 16, 15],
       [14, 13, 12, 11, 10],
       [ 9,  8,  7,  6,  5],
       [ 4,  3,  2,  1,  0]])

In [22]:
arr10=np.arange(225).reshape(3,15,5)
arr10

array([[[  0,   1,   2,   3,   4],
        [  5,   6,   7,   8,   9],
        [ 10,  11,  12,  13,  14],
        [ 15,  16,  17,  18,  19],
        [ 20,  21,  22,  23,  24],
        [ 25,  26,  27,  28,  29],
        [ 30,  31,  32,  33,  34],
        [ 35,  36,  37,  38,  39],
        [ 40,  41,  42,  43,  44],
        [ 45,  46,  47,  48,  49],
        [ 50,  51,  52,  53,  54],
        [ 55,  56,  57,  58,  59],
        [ 60,  61,  62,  63,  64],
        [ 65,  66,  67,  68,  69],
        [ 70,  71,  72,  73,  74]],

       [[ 75,  76,  77,  78,  79],
        [ 80,  81,  82,  83,  84],
        [ 85,  86,  87,  88,  89],
        [ 90,  91,  92,  93,  94],
        [ 95,  96,  97,  98,  99],
        [100, 101, 102, 103, 104],
        [105, 106, 107, 108, 109],
        [110, 111, 112, 113, 114],
        [115, 116, 117, 118, 119],
        [120, 121, 122, 123, 124],
        [125, 126, 127, 128, 129],
        [130, 131, 132, 133, 134],
        [135, 136, 137, 138, 139],
        [140, 141,

In [ ]:
### slicing in 3d array
# syntax

In [25]:
arr10[0:,1:4]

array([[[  5,   6,   7,   8,   9],
        [ 10,  11,  12,  13,  14],
        [ 15,  16,  17,  18,  19]],

       [[ 80,  81,  82,  83,  84],
        [ 85,  86,  87,  88,  89],
        [ 90,  91,  92,  93,  94]],

       [[155, 156, 157, 158, 159],
        [160, 161, 162, 163, 164],
        [165, 166, 167, 168, 169]]])

In [ ]:
np.max(arr8)
np.min(arr8)
np.sum(arr8)
np.mean(arr8)
h